version: '3.7'

services:

  postgres:
    image: postgres:13
    container_name: crypto_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase
    container_name: crypto_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.6.3
    container_name: airflow_init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/crypto
      AIRFLOW__WEBSERVER__SECRET_KEY: super_secret_key_123
    command: bash -c "airflow db init"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.6.3
    container_name: airflow_web
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/crypto
      AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: UTC
      AIRFLOW__WEBSERVER__SECRET_KEY: super_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./init_admin.sh:/opt/airflow/init_admin.sh
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jars:/opt/spark/jars
    user: root
    env_file:
      - .env
    command: >
      bash -c "airflow db upgrade &&
               bash /opt/airflow/init_admin.sh &&
               airflow webserver"

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache/airflow:2.6.3
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/crypto
      AIRFLOW__WEBSERVER__SECRET_KEY: super_secret_key_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - airflow_logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jars:/opt/spark/jars
    user: root
    env_file:
      - .env
    command: bash -c "airflow scheduler"

volumes:
  pgdata:
  airflow_logs:
